name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and deploy the Docker image
        run: |
          docker build -t udagram-frontend ./udagram-frontend
          docker tag udagram-frontend ifeoh/udagram-frontend:v2
          docker build -t reverseproxy ./reverseproxy
          docker tag reverseproxy ifeoh/reverseproxy
          docker build -t udagram-api-feeds ./udagram-api-feeds
          docker tag udagram-api-feeds ifeoh/udagram-api-feeds
          docker build -t udagram-api-users ./udagram-api-users
          docker tag udagram-api-users ifeoh/udagram-api-users
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ifeoh/udagram-api-feed
          docker push ifeoh/udagram-api-user
          docker push ifeoh/udagram-frontend:v2
          docker push ifeoh/reverseproxy
